apiVersion: v1
kind: ReplicationController
metadata:
  name: couchbase-master-rc
spec:
  replicas: 1
  selector:
    app: couchbase-master-pod
  template:
    metadata:
      labels:
        app: couchbase-master-pod
    spec:
      containers:
      - name: couchbase-master
        image: cr.yandex/<REGISTRY_ID>/ubuntu:couchbase
        env:
          - name: TYPE
            value: MASTER
        ports:
        - containerPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-master-service
spec:
  selector:
    app: couchbase-master-pod
  type: NodePort
  ports:
    - name: admin
      port: 8091
      protocol: TCP
