# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(846, 540)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.status.setMouseTracking(True)
        self.status.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setWordWrap(True)
        self.status.setOpenExternalLinks(False)
        self.status.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.UserDataEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.UserDataEdit.setObjectName("UserDataEdit")
        self.verticalLayout_3.addWidget(self.UserDataEdit)
        self.writeButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeButton.setObjectName("writeButton")
        self.verticalLayout_3.addWidget(self.writeButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.KeyData = QtWidgets.QTextEdit(self.centralwidget)
        self.KeyData.setMaximumSize(QtCore.QSize(16777215, 242))
        self.KeyData.setObjectName("KeyData")
        self.verticalLayout_2.addWidget(self.KeyData)
        self.UserData = QtWidgets.QTextBrowser(self.centralwidget)
        self.UserData.setObjectName("UserData")
        self.verticalLayout_2.addWidget(self.UserData)
        self.readButton = QtWidgets.QPushButton(self.centralwidget)
        self.readButton.setFlat(False)
        self.readButton.setObjectName("readButton")
        self.verticalLayout_2.addWidget(self.readButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status.setText(_translate("MainWindow", "Info"))
        self.UserDataEdit.setPlaceholderText(_translate("MainWindow", "write user data here"))
        self.writeButton.setText(_translate("MainWindow", "WriteUser"))
        self.KeyData.setPlaceholderText(_translate("MainWindow", "write key data here"))
        self.UserData.setPlaceholderText(_translate("MainWindow", "here will ne user data"))
        self.readButton.setText(_translate("MainWindow", "ReadUser"))
